name: Terraform Plan
on:
  pull_request:
    branches:      
      - main
      - feature/*
    types:
      - opened
      - synchronize

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Terraform Init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
