name: Terraform Apply
on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:

    

      - name: Checkout Repository
        uses: actions/checkout@v1     
       
      

      - name: Terraform Apply
        run: |
           terraform apply -auto-approve 
  

      

     