name: Terraform Apply
on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:    

      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1  

      - name: Terraform Init
        run: terraform init   
        
      - name: Download tfplan Artifact
        uses: dawidd6/action-download-artifact@v2
        with: 
          name: tfplan
          workflow_conclusion: success
          workflow: terraform-plan.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ github.event.pull_request.number }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        

      

     
     