name: Terraform Apply
on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9 

      - name: Checkout Repository
        uses: actions/checkout@v1     
        
      - name: Terraform Apply
        run: |
         mkdir tfstate
         terraform apply -auto-approve tfplan.tf -state-out=tfstate/terraform.tfstate

      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: tfplan
          path: tfplan

      

     