name: Terraform Apply
on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:

    

      - name: Checkout Repository
        uses: actions/checkout@v1     
       
      - name: init
        uses: terraform init  
       

      - name: Terraform Apply
        run: terraform apply tfplan
  

      

     